### PR TITLE
docs(README): fix wrong semicolon in example

### PR DESCRIPTION
**Pull request by JSteunou**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@JSteunou Please close and reopen the PR to trigger the CLA Bot again to/and sign the CLA :)

**Comment by michael-ciniawsky** [comment]
@JSteunou friendly ping 😛 , please close and reopen the PR and sign the CLA, otherwise I need to close the PR  for legal reasons 😞

**Comment by d3viant0ne** [comment]
@JSteunou - This can't be merged without a signed CLA

**Comment by evilebottnawi** [comment]
@JSteunou friendly ping

**Comment by JSteunou** [comment]
Oopsy sorry guys I did not receive notifications for this one.

Done ;)

**Comment by evilebottnawi** [comment]
@JSteunou thanks!

**Pull request merged**
