### PR TITLE
fix: invalid JSON.parse(`.babelrc`)

### PR DESCRIPTION
**Pull request by Coobaha**

### CODE REVIEW

**Comment by ericclemmons** [comment]
Whoa, good catch!

**Comment by ericclemmons** [comment]
@insin Thoughts on this?

**Comment by insin** [comment]
Valid `.babelrc` files may be invalid JSON, as Babel uses [`json5`](https://github.com/json5/json5) to parse it.

We should do the same.

**Comment by michael-ciniawsky** [comment]
`babelrc`needs to be parsed by `json5` parser then and this PR won't fix the issue ?

**Comment by Coobaha** [comment]
Right, now `json5` is used

**Pull request merged**
