### PR TITLE
chore: add issue and pr templates

### PR DESCRIPTION
**Pull request by snitin315**
Add Issue and PR templates.

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
Lets also add contributing.md

**Comment by snitin315** [comment]
Already present https://github.com/webpack-contrib/npm-install-webpack-plugin/blob/master/.github/CONTRIBUTING.md

**Review by anshumanv — APPROVED** [review]

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
To be honestly I think we can create a repository where we put all the standard templates/labels/badges and update them everywhere (i.e. include script link `npm webpack-org update`), what do you think?

**Comment by snitin315** [comment]
> To be honestly I think we can create a repository where we put all the standard templates/labels/badges and update them everywhere (i.e. include script link `npm webpack-org update`), what do you think?

Sounds good to me 👍🏻

**Comment by alexander-akait** [comment]
Ideally we need `webpack init --template webpack`, and create all simple files, like `.editorconfig`, issue templates, `lint-staged.config.js`, `husky` + packages.json with our basic scripts, I will merge this as is here, but let's start to do it too

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
